# Generated by Django 4.2.1 on 2023-06-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('necta', 'necta'), ('admin', 'admin')], max_length=20),
        ),
    ]
