# Generated by Django 3.2.18 on 2023-07-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='avarage_marks',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='capacity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
