# Generated by Django 3.2.18 on 2023-07-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230712_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='average_marks',
            field=models.FloatField(),
        ),
    ]
